project:
  type: website
  output-dir: docs
website:
  title: "Mon portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: about.qmd
        text: À propos
format:
  html:
    theme: cosmo
    toc: true
    resources: 
      - "public/moon_boss_model/*.glb"
      - "public/moon_boss_model/*.png"
      - "public/oruk_chef_model/*.glb"
      - "public/oruk_chef_model/*.png"